### PR TITLE
Windows build fixed replacing bash per node

### PR DESCRIPTION
**Pull request by tzkmx**
Building over #123, I'm replacing the build script requiring bash by a native script running through node.

It requires node > 8.5.0 as it is using `fs.copyFile`

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@tzkmx Thanks for PR and sorry for the delay.

I took alternative approach to this problem and rewrote how caching is working so it doesn't need shell script or fs.stat check.
Cache is downloaded when you run `npm install` or `yarn`.
Would be great if you test HEAD on your Windows machine.

I also working on simplifying build procedure for GitHub pages branch.

**Comment by tzkmx** [comment]
I'm sorry but I can't understand, build-public is still a bash script, so it doesn't work on windows.

**Comment by IvanGoncharov** [comment]
> I'm sorry but I can't understand, build-public is still a bash script, so it doesn't work on windows.

Sorry, it's what happens if you copy paste comments between issues.
* `npm run download` should work on Windows.
* `npm run build-public` I think current build procedure is too complex and I have a few ideas how to simplify it to a single command and then put directly into `package.json`.

**Comment by tzkmx** [comment]
Sooooo, based in what I've read in download.js using sync functions, and certainly the async with callbacks looks pretty scary, I've reworked the proposal to use a node script instead of keeping the bash based one, in order to allow people using windows to use the build script.

If it is possible and you'd like help with the ideas to simplify the scripts, please let me know and I'll see what can I do to help further.

**Comment by IvanGoncharov** [comment]
> Sooooo, based in what I've read in download.js using sync functions, and certainly the async with callbacks looks pretty scary,

Agree 👍 What do you think about b2c1e5c18d2e2ef99c6dbe21d6e160e2d54cfad3?

**Comment by IvanGoncharov** [comment]
> If it is possible and you'd like help with the ideas to simplify the scripts, please let me know and I'll see what can I do to help further.

I made `npm run build-public` windows-friendly in b2990f10971a4a82c52f77f9a3dade0ea5c35316. Would be great if you could test it?

**Pull request closed without merging**
