### PR TITLE
Enable SW API without graphiQL

### LINKED ISSUE #127: Expose API for outside testing
Could you expose the API without the GraphiQL interface?

So other people can send requests to the SWAPI GraphQL endpoint in order to tests GraphQL Clients.

- [ ] GET
- [ ] POST

### PR DESCRIPTION
**Pull request by deinok**
Closes #127 

cc: @wincent

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@deinok It's already supported just provide `Accept: application/json` HTTP Header in your request. If you can change header you can add `raw=true` query argument to your URL.
**Note**: You can do this only to the local server you started with `npm start`.

**Comment by deinok** [comment]
Yeah, the problem is that we want to do it via http://graphql.org/swapi-graphql/ and following this spec:

- http://graphql.org/swapi-graphql/
- http://graphql.org/swapi-graphql/

So `raw` is not allowed :(

**Comment by IvanGoncharov** [comment]
@deinok Web version (http://graphql.org/swapi-graphql) is run by totally different file:
https://github.com/graphql/swapi-graphql/blob/master/src/public/swapi.js
So it doesn't execute any server code at all, everything is done purely inside your browser.

It was discussed previously and here is Facebook position on this question:
https://github.com/graphql/swapi-graphql/issues/83#issuecomment-306247326

As a workaround, you can use our `swapi.apis.guru` server which supports both GET and POST.

**Comment by deinok** [comment]
Thanks @IvanGoncharov that last link is what I need.
A link in the README.md of this project will be usefull for people like me.
Thanks ;)

**Pull request closed without merging**
