### PR TITLE
This converts all fields at the root to be non-relay

### PR DESCRIPTION
**Pull request by schrockn**

### CODE REVIEW

**Comment by leebyron** [comment]
I'm a big fan of the simpler connection model. This is going to be something a lot of GraphQL n00bs look at, and minimizing noisy concepts is a win.

However I think we should keep `id`/`Node` as a holdout for those playing with Relay and pointing at this repo. Dropping connections means that Relay won't do pagination for you, but dropping id/Node means Relay won't do caching/deduping - which is really valuable when it works.

**Comment by schrockn** [comment]
Ok that makes sense I'll add them back

**Comment by schrockn** [comment]
Naturally I would prefer if relay could take care of this client-side but I'll live with it :-P

**Comment by dschafer** [comment]
@leebyron / @schrockn / I decided on the approach in #3 which contains a simpler connection model.

**Pull request closed without merging**
