### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by AGS-**
Made everything prettier

### CODE REVIEW

**Comment by AGS-** [comment]
Hmm, build is failing for some reason. Still need to fix that

**Comment by wincent** [comment]
Also want to tweak the lint config (lots of warnings).

**Comment by AGS-** [comment]
Should I just go ahead and set the lint configs to 0 for now?

**Comment by wincent** [comment]
We should bump the max-len to 120 [like I did here](https://github.com/graphql/graphql-language-service/commit/5d0ffd1a33a2c53fd3f9934e0c1bbcfb99bf4407), and the others I would adjust them. (I don't know if turning them off is the right thing, haven't looked at the rule configs.)

**Comment by asiandrummer** [comment]
@AGS- should I close this one out? Would you mind attending to this if we still want this?

**Comment by wincent** [comment]
Re-did this as #98.

**Pull request closed without merging**
